# Recommended resources
<br>
Data visualisation is the visual representation of patterns in data. An efficient data visualisation makes data more understandable.

## Resouces for the ggplot2 package
 -   [Data Visualization with ggplot2 Cheat Sheet - RStudio](https://rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)
<br>
 -   [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/index.html)
<br>
 -   [Data Visualization in R with ggplot2](https://altaf-ali.github.io/ggplot_tutorial/index.html)
<br>
 -   [Top 50 ggplot2 Visualizations - The Master List (With Full R Code)](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
<br>

## Resouces for graphs or data visualization in academic research

 -   [Ten guidelines for effective data visualization in scientific publications](https://www.sciencedirect.com/science/article/pii/S1364815210003270)
<br>
 -  [Beyond Bar and Line Graphs: Time for a New Data Presentation Paradigm](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002128)
<br>
 -  [How to Write a Paper](http://www-mech.eng.cam.ac.uk/mmd/ashby-paper-V6.pdf)
<br>
 -  [R Graphics Cookbook, 2nd edition](https://r-graphics.org/index.html)
<br>
 -  [Data visualization beginner's guide: a definition, examples, and learning resources](https://www.tableau.com/learn/articles/data-visualization)
<br>
 -  [From Data to Viz](https://www.data-to-viz.com/)
<br>
 -  [The R Graph Gallery](https://www.r-graph-gallery.com/index.html)
<br>
  
## How to find more useful resources 
  
 -  [GOOGLE](https://www.google.com/)
